# Copyright (C) 2017 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved
# This file is available under the MIT license.

- hosts: all
  gather_facts: False
  roles:
  - defunctzombie.coreos-bootstrap
